@AppliedSoftware_HostAddress = http://localhost:5071
@JWT = eyJhbGciOiJSUzI1NiIsImtpZCI6IjNhM2JkODk4ZGE1MGE4OWViOWUxY2YwYjdhN2VmZTM1OTNkNDEwNjgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcGFnZXR1cm5lci1ib29rc3RvcmUiLCJhdWQiOiJwYWdldHVybmVyLWJvb2tzdG9yZSIsImF1dGhfdGltZSI6MTcwMTc5ODM1NiwidXNlcl9pZCI6IkltZ1p3S3dIaGJRU0Q5ZlI0SGFna0NHbGNIdTEiLCJzdWIiOiJJbWdad0t3SGhiUVNEOWZSNEhhZ2tDR2xjSHUxIiwiaWF0IjoxNzAxODA0MDU2LCJleHAiOjE3MDE4MDc2NTYsImVtYWlsIjoiZ2l0QGl0emRldnMuZGV2IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImdpdEBpdHpkZXZzLmRldiJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.TlQ8pt-zAVe8ptI-lmbf2SxCT-bpTUY39Py1Tk4ky4D33LU9VmB70TssGbnpoODUY5ArE344l-GSGwfqF7DWSk0tF7D5uB94-oMTuAIbC88ebb5dZx5t9UecyyK-Hmg9l8kU_RdoUEByS1zLMOhXyJdkrFoDSI9Wj3rn2lk6uMiSxtN2v5rpKFlEcc-GoXS9Div1mF0xeCf8VyQZZ2fSemt9bpzX1W2nziTzqDyV_WR--52isKrQBNWTLe1DBi59jprBiI97Jd2IrZyrnzQ_YmuO1VtupMq5UhSf4wh7dwXmN7FTwJvyLWJeoixqgBoNHEqYe_fXGDW0wBruGg6xUw


GET {{AppliedSoftware_HostAddress}}/api/v1/packages
Accept: application/json
Authorization: Bearer {{JWT}}

###
